// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liukeshao/echo-admin/ent/org"
)

// OrgCreate is the builder for creating a Org entity.
type OrgCreate struct {
	config
	mutation *OrgMutation
	hooks    []Hook
}

// SetDeleteTime sets the "delete_time" field.
func (oc *OrgCreate) SetDeleteTime(i int64) *OrgCreate {
	oc.mutation.SetDeleteTime(i)
	return oc
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (oc *OrgCreate) SetNillableDeleteTime(i *int64) *OrgCreate {
	if i != nil {
		oc.SetDeleteTime(*i)
	}
	return oc
}

// SetCreateTime sets the "create_time" field.
func (oc *OrgCreate) SetCreateTime(t time.Time) *OrgCreate {
	oc.mutation.SetCreateTime(t)
	return oc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (oc *OrgCreate) SetNillableCreateTime(t *time.Time) *OrgCreate {
	if t != nil {
		oc.SetCreateTime(*t)
	}
	return oc
}

// SetUpdateTime sets the "update_time" field.
func (oc *OrgCreate) SetUpdateTime(t time.Time) *OrgCreate {
	oc.mutation.SetUpdateTime(t)
	return oc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (oc *OrgCreate) SetNillableUpdateTime(t *time.Time) *OrgCreate {
	if t != nil {
		oc.SetUpdateTime(*t)
	}
	return oc
}

// SetName sets the "name" field.
func (oc *OrgCreate) SetName(s string) *OrgCreate {
	oc.mutation.SetName(s)
	return oc
}

// SetDisplayName sets the "display_name" field.
func (oc *OrgCreate) SetDisplayName(s string) *OrgCreate {
	oc.mutation.SetDisplayName(s)
	return oc
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (oc *OrgCreate) SetNillableDisplayName(s *string) *OrgCreate {
	if s != nil {
		oc.SetDisplayName(*s)
	}
	return oc
}

// SetDescription sets the "description" field.
func (oc *OrgCreate) SetDescription(s string) *OrgCreate {
	oc.mutation.SetDescription(s)
	return oc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (oc *OrgCreate) SetNillableDescription(s *string) *OrgCreate {
	if s != nil {
		oc.SetDescription(*s)
	}
	return oc
}

// SetLogo sets the "logo" field.
func (oc *OrgCreate) SetLogo(s string) *OrgCreate {
	oc.mutation.SetLogo(s)
	return oc
}

// SetStatus sets the "status" field.
func (oc *OrgCreate) SetStatus(s string) *OrgCreate {
	oc.mutation.SetStatus(s)
	return oc
}

// SetType sets the "type" field.
func (oc *OrgCreate) SetType(s string) *OrgCreate {
	oc.mutation.SetType(s)
	return oc
}

// SetID sets the "id" field.
func (oc *OrgCreate) SetID(i int64) *OrgCreate {
	oc.mutation.SetID(i)
	return oc
}

// Mutation returns the OrgMutation object of the builder.
func (oc *OrgCreate) Mutation() *OrgMutation {
	return oc.mutation
}

// Save creates the Org in the database.
func (oc *OrgCreate) Save(ctx context.Context) (*Org, error) {
	if err := oc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrgCreate) SaveX(ctx context.Context) *Org {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OrgCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OrgCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OrgCreate) defaults() error {
	if _, ok := oc.mutation.DeleteTime(); !ok {
		v := org.DefaultDeleteTime
		oc.mutation.SetDeleteTime(v)
	}
	if _, ok := oc.mutation.CreateTime(); !ok {
		if org.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized org.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := org.DefaultCreateTime()
		oc.mutation.SetCreateTime(v)
	}
	if _, ok := oc.mutation.UpdateTime(); !ok {
		if org.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized org.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := org.DefaultUpdateTime()
		oc.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (oc *OrgCreate) check() error {
	if _, ok := oc.mutation.DeleteTime(); !ok {
		return &ValidationError{Name: "delete_time", err: errors.New(`ent: missing required field "Org.delete_time"`)}
	}
	if _, ok := oc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Org.create_time"`)}
	}
	if _, ok := oc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Org.update_time"`)}
	}
	if _, ok := oc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Org.name"`)}
	}
	if v, ok := oc.mutation.Name(); ok {
		if err := org.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Org.name": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Logo(); !ok {
		return &ValidationError{Name: "logo", err: errors.New(`ent: missing required field "Org.logo"`)}
	}
	if v, ok := oc.mutation.Logo(); ok {
		if err := org.LogoValidator(v); err != nil {
			return &ValidationError{Name: "logo", err: fmt.Errorf(`ent: validator failed for field "Org.logo": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Org.status"`)}
	}
	if v, ok := oc.mutation.Status(); ok {
		if err := org.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Org.status": %w`, err)}
		}
	}
	if _, ok := oc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Org.type"`)}
	}
	if v, ok := oc.mutation.GetType(); ok {
		if err := org.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Org.type": %w`, err)}
		}
	}
	return nil
}

func (oc *OrgCreate) sqlSave(ctx context.Context) (*Org, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OrgCreate) createSpec() (*Org, *sqlgraph.CreateSpec) {
	var (
		_node = &Org{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(org.Table, sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt64))
	)
	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := oc.mutation.DeleteTime(); ok {
		_spec.SetField(org.FieldDeleteTime, field.TypeInt64, value)
		_node.DeleteTime = value
	}
	if value, ok := oc.mutation.CreateTime(); ok {
		_spec.SetField(org.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := oc.mutation.UpdateTime(); ok {
		_spec.SetField(org.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := oc.mutation.Name(); ok {
		_spec.SetField(org.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := oc.mutation.DisplayName(); ok {
		_spec.SetField(org.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := oc.mutation.Description(); ok {
		_spec.SetField(org.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := oc.mutation.Logo(); ok {
		_spec.SetField(org.FieldLogo, field.TypeString, value)
		_node.Logo = value
	}
	if value, ok := oc.mutation.Status(); ok {
		_spec.SetField(org.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := oc.mutation.GetType(); ok {
		_spec.SetField(org.FieldType, field.TypeString, value)
		_node.Type = value
	}
	return _node, _spec
}

// OrgCreateBulk is the builder for creating many Org entities in bulk.
type OrgCreateBulk struct {
	config
	err      error
	builders []*OrgCreate
}

// Save creates the Org entities in the database.
func (ocb *OrgCreateBulk) Save(ctx context.Context) ([]*Org, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Org, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OrgCreateBulk) SaveX(ctx context.Context) []*Org {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OrgCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OrgCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
