// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cluster is the predicate function for cluster builders.
type Cluster func(*sql.Selector)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleBinding is the predicate function for rolebinding builders.
type RoleBinding func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
